version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-resume-prod
    ports:
      - "3010:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Add any other production environment variables here
      # EXAMPLE_VAR: "example_value"
